In [93]:
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,StandardScaler,PolynomialFeatures

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression, LinearRegression

from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import GridSearchCV

from sklearn.tree import DecisionTreeClassifier

import warnings
warnings.filterwarnings('ignore')

In [2]:
train = pd.read_csv(r'C:\Users\vpsiv\Desktop\Swe - DS\Hackathon\train_hackathon.csv')

In [3]:
train[:100]

id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0     1    Male   44                1         28.0                   0   
1     2    Male   76                1          3.0                   0   
2     3    Male   47                1         28.0                   0   
3     4    Male   21                1         11.0                   1   
4     5  Female   29                1         41.0                   1   
..  ...     ...  ...              ...          ...                 ...   
95   96  Female   23                1         30.0                   0   
96   97    Male   50                1         28.0                   0   
97   98  Female   62                1         28.0                   0   
98   99  Female   21                1          2.0                   0   
99  100  Female   24                1          7.0                   1   

   Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  \
0    > 2 Years            Yes         40454.0                  26.0      217   
1     1-2 Year             No         33536.0                  26.0      183   
2    > 2 Years            Yes         38294.0                  26.0       27   
3     < 1 Year             No         28619.0                 152.0      203   
4     < 1 Year             No         27496.0                 152.0       39   
..         ...            ...             ...                   ...      ...   
95    < 1 Year             No         26689.0                 152.0      254   
96    1-2 Year            Yes         46995.0                  52.0      291   
97   > 2 Years            Yes         41892.0                 155.0      114   
98    < 1 Year            Yes         34274.0                 152.0       79   
99    < 1 Year            Yes          2630.0                 160.0       68   

    Response  
0          1  
1          0  
2          1  
3          0  
4          0  
..       ...  
95         0  
96         0  
97         0  
98         0  
99         0  

[100 rows x 12 columns]

In [4]:
train.shape

(381109, 12)

In [5]:
test = pd.read_csv(r'C:\Users\vpsiv\Desktop\Swe - DS\Hackathon\test_hackathon.csv')

In [6]:
test.shape

(127037, 11)

In [7]:
test[:10]

id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0  381110    Male   25                1         11.0                   1   
1  381111    Male   40                1         28.0                   0   
2  381112    Male   47                1         28.0                   0   
3  381113    Male   24                1         27.0                   1   
4  381114    Male   27                1         28.0                   1   
5  381115    Male   22                1         30.0                   1   
6  381116  Female   51                1         37.0                   1   
7  381117    Male   25                1         41.0                   1   
8  381118    Male   42                1         41.0                   0   
9  381119  Female   37                1         12.0                   1   

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  
0    < 1 Year             No         35786.0                 152.0       53  
1    1-2 Year            Yes         33762.0                   7.0      111  
2    1-2 Year            Yes         40050.0                 124.0      199  
3    < 1 Year            Yes         37356.0                 152.0      187  
4    < 1 Year             No         59097.0                 152.0      297  
5    < 1 Year             No         40207.0                 152.0      266  
6    1-2 Year             No         40118.0                  26.0      107  
7    < 1 Year             No         23375.0                 152.0      232  
8    1-2 Year            Yes          2630.0                  26.0      277  
9    1-2 Year             No         27124.0                 124.0      133

In [8]:
test.columns

Index(['id', 'Gender', 'Age', 'Driving_License', 'Region_Code',
       'Previously_Insured', 'Vehicle_Age', 'Vehicle_Damage', 'Annual_Premium',
       'Policy_Sales_Channel', 'Vintage'],
      dtype='object')

In [9]:
train.columns

Index(['id', 'Gender', 'Age', 'Driving_License', 'Region_Code',
       'Previously_Insured', 'Vehicle_Age', 'Vehicle_Damage', 'Annual_Premium',
       'Policy_Sales_Channel', 'Vintage', 'Response'],
      dtype='object')

In [10]:
train.isna().sum()

id                      0
Gender                  0
Age                     0
Driving_License         0
Region_Code             0
Previously_Insured      0
Vehicle_Age             0
Vehicle_Damage          0
Annual_Premium          0
Policy_Sales_Channel    0
Vintage                 0
Response                0
dtype: int64

In [11]:
train.dtypes

id                        int64
Gender                   object
Age                       int64
Driving_License           int64
Region_Code             float64
Previously_Insured        int64
Vehicle_Age              object
Vehicle_Damage           object
Annual_Premium          float64
Policy_Sales_Channel    float64
Vintage                   int64
Response                  int64
dtype: object

In [12]:
train['Gender'].value_counts()

Gender
Male      206089
Female    175020
Name: count, dtype: int64

In [108]:
train['Age'].value_counts()

Age
24    25960
23    24256
22    20964
25    20636
21    16457
      ...  
81       56
82       29
83       22
84       11
85       11
Name: count, Length: 66, dtype: int64

In [110]:
train['Driving_License'].value_counts()

Driving_License
1    380297
0       812
Name: count, dtype: int64

In [112]:
train['Region_Code'].value_counts()

Region_Code
28.0    106415
8.0      33877
46.0     19749
41.0     18263
15.0     13308
30.0     12191
29.0     11065
50.0     10243
3.0       9251
11.0      9232
36.0      8797
33.0      7654
47.0      7436
35.0      6942
6.0       6280
45.0      5605
37.0      5501
18.0      5153
48.0      4681
14.0      4678
39.0      4644
10.0      4374
21.0      4266
2.0       4038
13.0      4036
7.0       3279
12.0      3198
9.0       3101
27.0      2823
32.0      2787
43.0      2639
17.0      2617
26.0      2587
25.0      2503
24.0      2415
38.0      2026
0.0       2021
16.0      2007
31.0      1960
23.0      1960
20.0      1935
49.0      1832
4.0       1801
34.0      1664
19.0      1535
22.0      1309
40.0      1295
5.0       1279
1.0       1008
44.0       808
42.0       591
52.0       267
51.0       183
Name: count, dtype: int64

In [114]:
train['Previously_Insured'].value_counts() 

Previously_Insured
0    206481
1    174628
Name: count, dtype: int64

In [116]:
train['Vehicle_Age'].value_counts() 

Vehicle_Age
1-2 Year     200316
< 1 Year     164786
> 2 Years     16007
Name: count, dtype: int64

In [118]:
train['Vehicle_Damage'].value_counts() 

Vehicle_Damage
Yes    192413
No     188696
Name: count, dtype: int64

In [120]:
train['Policy_Sales_Channel'].value_counts() 

Policy_Sales_Channel
152.0    134784
26.0      79700
124.0     73995
160.0     21779
156.0     10661
          ...  
149.0         1
43.0          1
144.0         1
143.0         1
41.0          1
Name: count, Length: 155, dtype: int64

In [122]:
train['Vintage'].value_counts() 

Vintage
256    1418
73     1410
282    1397
158    1394
187    1392
       ... 
205    1235
89     1234
32     1230
224    1227
277    1226
Name: count, Length: 290, dtype: int64

In [124]:
train['Response'].value_counts() 

Response
0    334399
1     46710
Name: count, dtype: int64

In [126]:
X = train.drop(columns = ['Response', 'id'])
y = train['Response']

In [128]:
X[:5]

Gender  Age  Driving_License  Region_Code  Previously_Insured Vehicle_Age  \
0    Male   44                1         28.0                   0   > 2 Years   
1    Male   76                1          3.0                   0    1-2 Year   
2    Male   47                1         28.0                   0   > 2 Years   
3    Male   21                1         11.0                   1    < 1 Year   
4  Female   29                1         41.0                   1    < 1 Year   

  Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  
0            Yes         40454.0                  26.0      217  
1             No         33536.0                  26.0      183  
2            Yes         38294.0                  26.0       27  
3             No         28619.0                 152.0      203  
4             No         27496.0                 152.0       39

In [130]:
y[:5]

0    1
1    0
2    1
3    0
4    0
Name: Response, dtype: int64

In [132]:
cat_features = ['Gender','Vehicle_Age','Vehicle_Damage','Driving_License','Previously_Insured']
num_features = ['Age','Region_Code','Annual_Premium','Policy_Sales_Channel','Vintage']

In [134]:
x_train, x_val, y_train, y_val = train_test_split(X,y,test_size=0.3, random_state = 24)

In [136]:
cat_transformer = Pipeline(steps=[('onehot',OneHotEncoder())])

In [138]:
num_transformer = Pipeline(steps=[('scale',StandardScaler())])

In [140]:
preprocessor = ColumnTransformer (transformers = [('categorical_transformer',cat_transformer,cat_features),
                                                  ('Numerical_transformer',num_transformer,num_features)])

In [142]:
model_pipeline = Pipeline(steps=[
    ('Preprocessing', preprocessor), 
    ('Logistic_regression_model', LogisticRegression())
])

In [144]:
model_pipeline

Pipeline(steps=[('Preprocessing',
                 ColumnTransformer(transformers=[('categorical_transformer',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder())]),
                                                  ['Gender', 'Vehicle_Age',
                                                   'Vehicle_Damage',
                                                   'Driving_License',
                                                   'Previously_Insured']),
                                                 ('Numerical_transformer',
                                                  Pipeline(steps=[('scale',
                                                                   StandardScaler())]),
                                                  ['Age', 'Region_Code',
                                                   'Annual_Premium',
                                                   'Policy_Sales_Channel',
                                                   'Vintage'])])),
                ('Logistic_regression_model', LogisticRegression())])

In [146]:
model_pipeline.fit(x_train,y_train)

Pipeline(steps=[('Preprocessing',
                 ColumnTransformer(transformers=[('categorical_transformer',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder())]),
                                                  ['Gender', 'Vehicle_Age',
                                                   'Vehicle_Damage',
                                                   'Driving_License',
                                                   'Previously_Insured']),
                                                 ('Numerical_transformer',
                                                  Pipeline(steps=[('scale',
                                                                   StandardScaler())]),
                                                  ['Age', 'Region_Code',
                                                   'Annual_Premium',
                                                   'Policy_Sales_Channel',
                                                   'Vintage'])])),
                ('Logistic_regression_model', LogisticRegression())])

In [148]:
train_pred = model_pipeline.predict(x_train)

In [150]:
val_pred = model_pipeline.predict(x_val)

In [152]:
accuracy_score(y_train, train_pred)

0.8767655261342849

In [154]:
accuracy_score(y_val, val_pred)

0.878967577164948

In [253]:
under_sampling = RandomUnderSampler()

In [255]:
train_underSample_X, train_y_under_sample = under_sampling.fit_resample(X, y)

In [257]:
train_underSample_X.shape , train_y_under_sample.shape

((93420, 10), (93420,))

In [259]:
yy = train_y_under_sample.to_frame()

In [261]:
Xtrsplit_us,Xtestsplit_us , ytrsplit_us , ytestsplit_us = train_test_split( train_underSample_X , yy , test_size=0.3 , random_state=44 )

In [267]:
model_pipeline.fit(Xtrsplit_us, ytrsplit_us)

Pipeline(steps=[('Preprocessing',
                 ColumnTransformer(transformers=[('categorical_transformer',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder())]),
                                                  ['Gender', 'Vehicle_Age',
                                                   'Vehicle_Damage',
                                                   'Driving_License',
                                                   'Previously_Insured']),
                                                 ('Numerical_transformer',
                                                  Pipeline(steps=[('scale',
                                                                   StandardScaler())]),
                                                  ['Age', 'Region_Code',
                                                   'Annual_Premium',
                                                   'Policy_Sales_Channel',
                                                   'Vintage'])])),
                ('Logistic_regression_model', LogisticRegression())])

In [269]:
train_pred_undersampled = model_pipeline.predict(Xtrsplit_us)

In [271]:
train_pred_undersampled

array([1, 1, 1, ..., 0, 1, 0], dtype=int64)

In [273]:
Val_pred_undersampled = model_pipeline.predict(Xtestsplit_us)

In [275]:
accuracy_undersample_test = accuracy_score(ytestsplit_us, Val_pred_undersampled)

In [277]:
accuracy_undersample_test

0.7867694283879255

In [279]:
accuracy_undersample_train = accuracy_score(ytrsplit_us, train_pred_undersampled)

In [281]:
accuracy_undersample_train

0.7829617396091385

In [287]:
print(f'Accuracy Train : {accuracy_score( ytrsplit_us, train_pred_undersampled)}')
print(f'classification_report : \n{classification_report(ytrsplit_us, train_pred_undersampled)}')
print(f'confusion_matrix :\n {confusion_matrix ( ytrsplit_us, train_pred_undersampled)}')
print('\n','=====================================================','\n')
print(f'Accuracy Test : {accuracy_score( ytestsplit_us, Val_pred_undersampled)}')
print(f'classification_report : \n{classification_report ( ytestsplit_us, Val_pred_undersampled)}')
print(f'confusion_matrix :\n {confusion_matrix ( ytestsplit_us, Val_pred_undersampled)}')

Accuracy Train : 0.7829617396091385
classification_report : 
              precision    recall  f1-score   support

           0       0.96      0.60      0.73     32833
           1       0.70      0.97      0.82     32561

    accuracy                           0.78     65394
   macro avg       0.83      0.78      0.78     65394
weighted avg       0.83      0.78      0.78     65394

confusion_matrix :
 [[19549 13284]
 [  909 31652]]


Accuracy Test : 0.7867694283879255
classification_report : 
              precision    recall  f1-score   support

           0       0.95      0.60      0.74     13877
           1       0.71      0.97      0.82     14149

    accuracy                           0.79     28026
   macro avg       0.83      0.78      0.78     28026
weighted avg       0.83      0.79      0.78     28026

confusion_matrix :
 [[ 8322  5555]
 [  421 13728]]


In [ ]:
#dt = DecisionTreeClassifier()

In [289]:
model_pipeline_DT = Pipeline(steps=[
    ('Preprocessing', preprocessor), 
    ('DTClassifier', DecisionTreeClassifier())
])

In [291]:
model_pipeline_DT.fit(Xtrsplit_us, ytrsplit_us)

Pipeline(steps=[('Preprocessing',
                 ColumnTransformer(transformers=[('categorical_transformer',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder())]),
                                                  ['Gender', 'Vehicle_Age',
                                                   'Vehicle_Damage',
                                                   'Driving_License',
                                                   'Previously_Insured']),
                                                 ('Numerical_transformer',
                                                  Pipeline(steps=[('scale',
                                                                   StandardScaler())]),
                                                  ['Age', 'Region_Code',
                                                   'Annual_Premium',
                                                   'Policy_Sales_Channel',
                                                   'Vintage'])])),
                ('DTClassifier', DecisionTreeClassifier())])

In [293]:
trainpred_us_DT = model_pipeline_DT.predict(Xtrsplit_us)

In [295]:
Valpred_us_DT = model_pipeline_DT.predict(Xtestsplit_us)

In [297]:
accuracy_Valpred_us_DT = accuracy_score(ytestsplit_us, Valpred_us_DT)

In [299]:
accuracy_trainpred_us_DT = accuracy_score(ytrsplit_us, trainpred_us_DT)

In [301]:
print(f'Accuracy Train DT: {accuracy_score(ytrsplit_us, trainpred_us_DT)}')
print(f'classification_report : \n{classification_report(ytrsplit_us, trainpred_us_DT)}')
print(f'confusion_matrix :\n {confusion_matrix (ytrsplit_us, trainpred_us_DT)}')
print('\n','=====================================================','\n')
print(f'Accuracy Test DT : {accuracy_score(ytestsplit_us, Valpred_us_DT)}')
print(f'classification_report : \n{classification_report (ytestsplit_us, Valpred_us_DT)}')
print(f'confusion_matrix :\n {confusion_matrix (ytestsplit_us, Valpred_us_DT)}')

Accuracy Train DT: 0.9999541242315809
classification_report : 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     32833
           1       1.00      1.00      1.00     32561

    accuracy                           1.00     65394
   macro avg       1.00      1.00      1.00     65394
weighted avg       1.00      1.00      1.00     65394

confusion_matrix :
 [[32833     0]
 [    3 32558]]


Accuracy Test DT : 0.7149075858131735
classification_report : 
              precision    recall  f1-score   support

           0       0.71      0.73      0.72     13877
           1       0.72      0.70      0.71     14149

    accuracy                           0.71     28026
   macro avg       0.72      0.72      0.71     28026
weighted avg       0.72      0.71      0.71     28026

confusion_matrix :
 [[10103  3774]
 [ 4216  9933]]


In [309]:
param = {
 'criterion': ['entropy'],
 'max_depth': [100],
 'max_features': ['sqrt'],
 'min_samples_leaf': [1],
 'min_samples_split':[5]
}

In [311]:
#grid = GridSearchCV(estimator= DecisionTreeClassifier(),param_grid=param ,scoring='accuracy', n_jobs=-1 , verbose=2)

In [313]:
model_pipeline_Dt_GSCV = Pipeline(steps=[
    ('Preprocessing', preprocessor), 
    ('DTClassifier_GSCV', GridSearchCV(estimator= DecisionTreeClassifier(),param_grid=param ,scoring='accuracy', n_jobs=-1 , verbose=2))
])

In [315]:
model_pipeline_Dt_GSCV.fit(Xtrsplit_us, ytrsplit_us)

Fitting 5 folds for each of 1 candidates, totalling 5 fits


Pipeline(steps=[('Preprocessing',
                 ColumnTransformer(transformers=[('categorical_transformer',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder())]),
                                                  ['Gender', 'Vehicle_Age',
                                                   'Vehicle_Damage',
                                                   'Driving_License',
                                                   'Previously_Insured']),
                                                 ('Numerical_transformer',
                                                  Pipeline(steps=[('scale',
                                                                   StandardScaler())]),
                                                  ['Age', 'Region_Code',
                                                   'Annual_Premium',
                                                   'Policy_Sales_Channel',
                                                   'Vintage'])])),
                ('DTClassifier_GSCV',
                 GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
                              param_grid={'criterion': ['entropy'],
                                          'max_depth': [100],
                                          'max_features': ['sqrt'],
                                          'min_samples_leaf': [1],
                                          'min_samples_split': [5]},
                              scoring='accuracy', verbose=2))])

In [319]:
Valpred_us_DT_GSCV = model_pipeline_Dt_GSCV.predict(Xtestsplit_us)
trainpred_us_DT_GSCV = model_pipeline_Dt_GSCV.predict(Xtrsplit_us)

print(f'Accuracy : {accuracy_score(ytrsplit_us, trainpred_us_DT_GSCV)}')
print(f'classification_report : \n{classification_report (ytrsplit_us, trainpred_us_DT_GSCV)}')
print(f'confusion_matrix :\n {confusion_matrix (ytrsplit_us, trainpred_us_DT_GSCV)}')
print('\n','=====================================================','\n')
print(f'Accuracy : {accuracy_score(ytestsplit_us, Valpred_us_DT_GSCV)}')
print(f'classification_report : \n{classification_report (ytestsplit_us, Valpred_us_DT_GSCV)}')
print(f'confusion_matrix :\n {confusion_matrix (ytestsplit_us, Valpred_us_DT_GSCV)}')

Accuracy : 0.9405144202832064
classification_report : 
              precision    recall  f1-score   support

           0       0.92      0.96      0.94     32833
           1       0.96      0.92      0.94     32561

    accuracy                           0.94     65394
   macro avg       0.94      0.94      0.94     65394
weighted avg       0.94      0.94      0.94     65394

confusion_matrix :
 [[31678  1155]
 [ 2735 29826]]


Accuracy : 0.7131948904588596
classification_report : 
              precision    recall  f1-score   support

           0       0.70      0.74      0.72     13877
           1       0.73      0.69      0.71     14149

    accuracy                           0.71     28026
   macro avg       0.71      0.71      0.71     28026
weighted avg       0.71      0.71      0.71     28026

confusion_matrix :
 [[10286  3591]
 [ 4447  9702]]
